language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: kSJHDOFxUxDf1DkBN7+9ThTOW95nhbKfHUsL2KzPNoNhLxxxTNEFnmZ7Q1kKrTz+gP/sLP1jJWCByLWH8VzkaSbqC9XSj3YoH4el0MkAkOgL7yWsCmqK+14lEBmsSiMH+GL26hfaiDw27tcwoJPtK7S2/CVTHzWGhiQkA88S62a84m55cUcwZWrT4cUanrgWeG7FtWMR4rG1QtowIDpgpFplwCeOba0lNPtIVJ031S6w6TetXskkOLLNfP+zIPrLoKPy4GBhx2exx/QTyxSsHAzeTXUzD4i5HC498esvyybi49o8lT9jaySgNqGrzBAucMFQMWqqyT0svns8NQr/E0HTtKz4L+ndbTWR7m9CUcAAXnOeMa0ob0uNtPyww7/s5Kq8u5ZUuD1M/ce18j4sCjj0OvXIRtk6xrYZ24rwNMk0K43q7qopq5QQo1dOqPFc5PnZaOrHlSMgouSpXLkgT1lWDLov8otFRFxngt67dUY1V65UnW3eo1xBgPmt4E49aQou2jofAAFX0eca3LzfeWMzMlBRFgOsvzT5mwQceirP2dClVYolD6jbO+AsSh6NWSY2uDStpGdLX6uZhg8Vd+TsbGoq2ss0GetvzMh4cs7CtNkaxwcL3lilmvmLShAgIeMHWoNkSE8jV/pfrT4vA45Pd6zxNDuOzzpDcn2bbGU=
  app: warm-brook-74008
  on:
    repo: AWAlemu/fullstack_app
